name: flutterfinal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  firebase_core: ^3.2.0
  firebase_auth: ^5.2.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  http: ^1.2.2
  file_picker: ^8.0.7
  cloud_firestore: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
 
  

flutter:
  uses-material-design: true
  assets:
  - assets/login1.jpg
  - assets/one.jpg
  - assets/background.jpg

flutter_icons:
  android: true
  ios: true 
  image_path: "assets/logo2.png"
  adaptive_icon_background: '#000000'
  adaptive_icon_foreground: "assets/logo2.png"
